// Action types
export const USERS_COORDINATES_RECEIVED = 'USERS_COORDINATES_RECEIVED';
export const WEATHER_IS_LOADING = 'WEATHER_IS_LOADING';
export const GET_WEATHER_SUCCESS = 'GET_WEATHER_SUCCESS';
