// Action types
export const USERS_COORDINATES_RECEIVED = 'USERS_COORDINATES_RECEIVED';
export const WEATHER_IS_LOADING = 'WEATHER_IS_LOADING';
export const GET_WEATHER_BY_COORDINATES_SUCCESS = 'GET_WEATHER_BY_COORDINATES_SUCCESS';
export const GET_WEATHER_BY_CITY_SUCCESS = 'GET_WEATHER_BY_CITY_SUCCESS';
export const TOGGLE_SEARCH_SCREEN = 'TOGGLE_SEARCH_SCREEN';
